version: '3'
services:
    nginx:
        build:
            context: docker/nginx
            dockerfile: Dockerfile
            args:
                - NGINXUSER=${NGINXUSER:-www-data}
                - NGINXGROUP=${NGINXGROUP:-www-data}
        container_name: nginx
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - .:/var/www/html:delegated
        restart: unless-stopped
        depends_on:
            - sdui
        networks:
            - sdui_network

    sdui:
        build:
            context: docker/laravel
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        container_name: sdui
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        restart: unless-stopped
        networks:
            - sdui_network

    scheduler:
        build:
            context: docker/scheduler
            dockerfile: Dockerfile
        container_name: scheduler
        volumes:
            - '.:/var/www/html'
        restart: unless-stopped
        networks:
            - sdui_network
        depends_on:
            - sdui

networks:
    sdui_network:
        driver: bridge
